{% set name = "vit-pytorch" %}
{% set version = "1.8.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz"
  sha256: 5d8c7bb5522ebeb895ca3e17c38d8ed8df3582240b1d80ed2a33161799f23045

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
    - setuptools
  run:
    - einops >=0.7.0
    - python >=3.6
    - pytorch >=1.10
    - torchvision

test:
  imports:
    - vit_pytorch
  source_files:
    - tests/test.py
  requires:
    - pytest
  commands:
    - pytest tests/*.py

about:
  home: "https://github.com/lucidrains/vit-pytorch"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Vision Transformer (ViT) - Pytorch"
  dev_url: https://github.com/lucidrains/vit-pytorch

extra:
  recipe-maintainers:
    - weiji14
