{% set name = "vit-pytorch" %}
{% set version = "1.11.7" %}
{% set python_min = "3.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz"
  sha256: 9960eae17062830280a08f2da368cea513f56bffaaedf3af77a8b37f12d57c89

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools
  run:
    - einops >=0.7.0
    - python >={{ python_min }}
    - pytorch >=1.10
    - torchvision

test:
  imports:
    - vit_pytorch
  source_files:
    - tests/test.py
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - pytest tests/*.py

about:
  home: "https://github.com/lucidrains/vit-pytorch"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Vision Transformer (ViT) - Pytorch"
  dev_url: https://github.com/lucidrains/vit-pytorch

extra:
  recipe-maintainers:
    - weiji14
