{% set name = "vit-pytorch" %}
{% set version = "1.8.8" %}
{% set python_min = "3.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz"
  sha256: 04b14868daf6bf805ac72727c7ef674516c5f1ffcc9c2588fa6c2cc4cf44ab85

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools
  run:
    - einops >=0.7.0
    - python >={{ python_min }}
    - pytorch >=1.10
    - torchvision

test:
  imports:
    - vit_pytorch
  source_files:
    - tests/test.py
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - pytest tests/*.py

about:
  home: "https://github.com/lucidrains/vit-pytorch"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Vision Transformer (ViT) - Pytorch"
  dev_url: https://github.com/lucidrains/vit-pytorch

extra:
  recipe-maintainers:
    - weiji14
