schema_version: 1

context:
  name: vit-pytorch
  version: "1.19.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: f55a3fd18199f878451e0e0e80f41696357c7b83d0738dffa6fd246a224370e1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=61
  run:
    - einops >=0.8.2
    - python >=${{ python_min }}
    - pytorch >=2.4
    - torchvision

tests:
  - python:
      imports:
        - vit_pytorch
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - tests/test_vit.py
    requirements:
      run:
        - pytest
        - python ${{ python_min }}.*
    script:
      - pytest --verbose tests/*.py

about:
  homepage: https://codeberg.org/lucidrains/vit-pytorch
  license: MIT
  license_file: LICENSE
  summary: Vision Transformer (ViT) - Pytorch

extra:
  recipe-maintainers:
    - weiji14
