schema_version: 1

context:
  name: vit-pytorch
  version: "1.15.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 9dd793ca55a9f6dfb61f1147d5bc257cd7502ebb0697960f5f6ef56733db608d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=61
  run:
    - einops >=0.7.0
    - python >=${{ python_min }}
    - pytorch >=1.10
    - torchvision

tests:
  - python:
      imports:
        - vit_pytorch
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - tests/test_vit.py
    requirements:
      run:
        - pytest
        - python ${{ python_min }}.*
    script:
      - pytest --verbose tests/*.py

about:
  homepage: https://github.com/lucidrains/vit-pytorch
  license: MIT
  license_file: LICENSE
  summary: Vision Transformer (ViT) - Pytorch

extra:
  recipe-maintainers:
    - weiji14
